return {}
-- return {
--   "nvimtools/none-ls.nvim", -- configure formatters & linters
--   lazy = true,
--   -- event = { "BufReadPre", "BufNewFile" }, -- to enable uncomment this
--   dependencies = {
--     "jay-babu/mason-null-ls.nvim",
--   },
--   config = function()
--     require("mason-null-ls").setup({
--       ensure_installed = {
--         "prettier",
--         "pylint",
--         "eslint_d",
--       }
--     })
--   end
-- }
